# Generated by Django 4.2.7 on 2024-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Egitmen',
            fields=[
                ('egitmen_id', models.AutoField(primary_key=True, serialize=False)),
                ('telefon', models.CharField(max_length=20)),
                ('dogum_tarihi', models.DateField()),
                ('cinsiyet', models.CharField(max_length=10)),
                ('ilgi_alani', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='ilgi_alani',
        ),
        migrations.AddField(
            model_name='user',
            name='rutbe',
            field=models.CharField(default='uye', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='ad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='cinsiyet',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sifre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='soyad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefon',
            field=models.CharField(max_length=20),
        ),
    ]
