# Generated by Django 4.2.7 on 2024-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0002_admin_egitmen_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
