version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    volumes:
      - .:/app
    depends_on:
      - web

volumes:
  postgres_data:
